travis:
  secure:
    BINSTAR_TOKEN: AmHsY/NoxAv73QLN1rJTJ1VB94z/OOsE2IwsWvmae4XB8umhX1jzmzSxYv3DBxp2WR9TFcNrdMj+uIi1XvsV1L5vCWP1jqroDTGYhNz+jOassHgL7kAFxMgJ1s33VR/jrDpHakSIv/AZWb2LF6n+bgPz8d/ZzJ9THh5myKozl2lVTVnogyZT6Kf9qxZUqgneUiSkgjYg+EheI9g/QZERBD3GeKwzC2e9G3Z6Ci7TBs0xDoPFwgL7jssu+umn5ucfSSU4eG44ezKR8PeKXGgpWowooblK59SlArcEBEQKvCnPKig+FAf1HAu/ZRdPH6+QRu5U7rBSHXLpMnZPxF3h/OOkKqBZVBGWc2RBCXtVNu1DwmwYkWFd153KkSIltdDVDUYZ6Fg4/D+6YTpnYUXtUnfDycVMpfovgJ7Orm3s624FsUfgTufKea+JBRtFEBkf5WAl7+XoK3TXHMsMlnyspfgibTVNtwpYGAaEJOd09Y8dNu1DEkf0k7MH59UHSQfXXgo2XvKzb6VwDay6VSUuGXYyUzni/OBb1nHivlZKezx9FL8Z129IWZ9jYrJrRjDCWnd/Dooep8ygydBA6oBl9HGEzfw9GCz5MLbj5XWXVZCtnhYhM24d0utbR4M7b78FMaOBQ77tEOq7gV7HqmNJTtvGOtUjJgqiYF8zLaJDBWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
